### ISSUE TITLE
Immediate refresh of drawn strokes on ONYX e-ink displays (RawDrawing)

### ISSUE THREAD

**Issue by TekkertheChaot** [saber-notes/saber#1195]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

One thing to make writing on e-ink-tablets like ONYX tablets way more comfortable is to update the pen stroke immediately as it is being drawn. This helps during writing, sketching and feels way more natural to the user.
With this I'm not refering to the normal "draw to UI"-call but to update the display directly. 

With the proposed solution, ONYX users have the ability to use higher quality display modes, which would increase display latency under normal usage (like its currently the case) except for pen strokes which update directly while being drawn.

### Solution

If I understand correctly, the onyx-sdk offers the functionality to directly and immediately refresh the display in the area where the pen-stroke is being drawn in. 

I think the way to do this, is by using the "RawDrawing"-Mode and using the RawInputCallback to quickly draw a bitmap to the display itself. This could reflect a rough estimate on the display on how the pen-stroke looks, that can be fully updated once the penis lifted from the display. [The official OnyxAndroidDemo project does this somewhat similarly](https://github.com/onyx-intl/OnyxAndroidDemo/blob/635a450bcb88cb0b8f70685f6d82a6c7865502bc/app/src/main/java/com/android/onyx/demo/scribble/ScribblePenUpRefreshDemoActivity.java#L92). 

[Notable](https://github.com/olup/notable/blob/6605e8826e0eca3047e5c388eea27598246c5871/app/src/main/java/com/olup/notable/classes/DrawCanvas.kt#L63) is another app that is specifically build for ONYX tablets that also utilizes the RawDrawing-mode. 
The official OnyxAndroidDemo project may also have a demo on how to refresh it immediately, but unfortunately,

### Saber version

0.21.2 GooglePlay (21020)

### Device

- Device: ONYX BOOX Tab Ultra
- OS: Android 11

**Comment by adil192** [comment]
This seems the same as what we currently have in [OnyxsdkPenArea.kt](https://github.com/saber-notes/saber/blob/main/packages/onyxsdk_pen/android/src/main/kotlin/com/example/onyxsdk_pen/OnyxsdkPenArea.kt).

You may be referring to how the screen doesn't fully refresh for 1s after you draw with the pen. This is [intentional](https://pub.dev/packages/onyxsdk_pen/changelog):

> 1.0.2
> Refresh the screen after 1s (default). This fixes the issue where after writing with the pen, the screen wouldn't respond to your finger.

You're free to submit PRs if you can improve the implementation, but I no longer have an Onyx device to test any further development

**Comment by TekkertheChaot** [comment]
>This seems the same as what we currently have in [OnyxsdkPenArea.kt](https://github.com/saber-notes/saber/blob/main/packages/onyxsdk_pen/android/src/main/kotlin/com/example/onyxsdk_pen/OnyxsdkPenArea.kt).

Oh, I have completely missed that, sorry!

>You may be referring to how the screen doesn't fully refresh for 1s after you draw with the pen. This is [intentional](https://pub.dev/packages/onyxsdk_pen/changelog)

Ahh, not quite. The intentional fix you've mentioned seems to be referring to the screen refresh after pen inactivity. This would coincide with the refreshing I have observed in the current version of the app. 
I've meant the immediate refresh while drawing.
Currently, it is completely dependent on the screen refresh mode:
![pen stroke comparison](https://github.com/saber-notes/saber/assets/17234581/1f04df41-a159-468b-973b-f77dae43cc3b)

> You're free to submit PRs if you can improve the implementation, but I no longer have an Onyx device to test any further development

Understandable and fair! Maybe this will be THE push for me to get into android app development... 😉

**Comment by adil192** [comment]
When I had my onyx boox note air2, it worked like the notable app did in your gif (https://github.com/saber-notes/saber/issues/186)
@ma-con Is it still working for you?

**Comment by adil192** [comment]
Can you confirm you downloaded Saber from the Play Store and not somewhere else like F-Droid?

**Comment by TekkertheChaot** [comment]
> When I had my onyx boox note air2, it worked like the notable app did in your gif (https://github.com/saber-notes/saber/issues/186)

Hmmm, weird. 🤔


>Can you confirm you downloaded Saber from the Play Store and not somewhere else like F-Droid?

Yeah, I got it from the play store:
![IMG_20240404_140748~2.jpg](https://github.com/saber-notes/saber/assets/17234581/42837b6b-03a0-4978-9981-34a851128608)

**Comment by TekkertheChaot** [comment]
I really want to rule out user error, before I dive into a self learning course for Android development. 
**Are there any accessible settings that could affect this?** 
Otherwise, Android Studio is downloading in the background... ;)

**Comment by favba** [comment]
I have an Onyx Boox Note Air 2 Plus and Saber installed from Google Play.
Saber used to have fast pen strokes but that hasn't worked for several months by now. I cannot remember which update broke this, but I can confirm (or at least give one more data point) that the fast pen strokes are not working anymore on Onyx Boox devices.

**Comment by ghost14622** [comment]
I have an Onyx Boox Note X3s and Saber installed from Github.
 The fast pen strokes are not working anymore on Onyx Boox devices. And when i was writing the whole screen would refresh but not the writing part. Hope we can fix it.

**Comment by TekkertheChaot** [comment]
As I am new to programming in dart (and flutter & kotlin for that matter) I am only slowly starting to understand how things are handled. 
Unfortunately, I cannot get the required OnyxpenSDK module running in flutter on my end. 
Something about how no module repo (maven, google, etc. ) is able to serve the referenced libraries. 
I think I am too inexperienced to get it working myself for now...

**Comment by ghost14622** [comment]
> As I am new to programming in dart (and flutter & kotlin for that matter) I am only slowly starting to understand how things are handled. Unfortunately, I cannot get the required OnyxpenSDK module running in flutter on my end. Something about how no module repo (maven, google, etc. ) is able to serve the referenced libraries. I think I am too inexperienced to get it working myself for now...

That's all right. We are lucky to have Saber. It's enough for now.

**Comment by adil192** [comment]
> I have Saber version 0.24.1 installed now and the instant stroke feature on my Onyx Note Air 2 plus is working again!

Glad to hear it!

**Comment by TekkertheChaot** [comment]
Just wanted to add: works on Boox Tab Ultra again too! thank you! @adil192 for the patch!

**Comment by tverbeke** [comment]
I experience the exact same issue described here with an ONYX BOOX Go 10.3 both with version 0.24.4 (F-Droid) and with version 0.24.5 (Play Store).  The OS on this device is Android 12. Please let me know if I can provide any other information.

**Comment by gilcu3** [comment]
I am facing this issue as well with the same device, using the current version from github `0.24.7` (the non FOSS that should contain `onyx-sdk`). Maybe the problem is that the lib is not up-to-date?

Should we open another issue given that the original one was fixed?

**Comment by gortiz** [comment]
I'm finding the same issue in a boox note 4c using 0.25.2 (google play). I won't be available probably until the end of the year, but if by then nobody was able to fix it, I can try to take a look.

**Comment by Iey4iej3** [comment]
> I experience the exact same issue described here with an ONYX BOOX Go 10.3 both with version 0.24.4 (F-Droid) and with version 0.24.5 (Play Store). The OS on this device is Android 12. Please let me know if I can provide any other information.

Does the issue persist for you on Go 10.3 with Play Store version (thus non-FOSS)? It seems to be gone on my device, but there is a more serious issue #1459
