### ISSUE TITLE
App crashes with many-paged PDF

### ISSUE THREAD

**Issue by rambonette** [saber-notes/saber#1516]
### Before submitting an issue, please check the following

- [x] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [x] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

I wanna actually start by saying that I'm aware of previous issues #771 , #1209 and #1385 but none of them got solved nor got much traction. I tried many of the user suggestions that were proposed there by users with no luck.

The app crashes consistently when loading an image-rich 500+ pages PDF.

I'd gladly provide some logs, but my Logs section is always empty no matter if I play/pause the section button.

### To reproduce

1. Open Saber
2. In the Home section tap on  '+'
3. Tap on Import note
4. Select the long PDF
5. Scroll to page 100
6. wait for it to crash

I recorded a small video which shows the steps that consistently bring Saber to crash. Sorry for the potato-quality video, but github wouldn't let me upload the original 13MB~.

https://github.com/user-attachments/assets/5adedd14-9337-4d23-b336-9279eee11f18

### Expected behavior

I'd expect Saber to:
- not crash
- implement a loading strategy which prioritizes scroll position

### Saber version

v0.26.3 F-Droid (26030)

### Device

- Device: Lenovo Idea Tab Pro 8GB RAM
- OS: Android 15

### Anything else?

Let me know if I can provide anything else. I've got some programming skills so I don't mind diving into some technical stuff.

**Comment by dreamAviator** [comment]
happens to me too, but faster
on my phone it takes a while but crashes too

**Comment by BulbLi** [comment]
On the Windows version, I also experience freezes and crashes when opening PDFs with a large number of pages.

**Comment by QubaB** [comment]
I am working on the fix, however it will need rework of internal cache of Saber. I published a draft of how to do it #1546 but it will take a time to finish and thoroughly test.

**Comment by rambonette** [comment]
> I am working on the fix, however it will need rework of internal cache of Saber. I published a draft of how to do it [#1546](https://github.com/saber-notes/saber/pull/1546) but it will take a time to finish and thoroughly test.

thanks @QubaB ! Let me know if you need any help with testing :)

**Comment by dreamAviator** [comment]
I tried testing it.
I created a new note from a 230page pdf, saved it and closed it and reopened. While the note opens, the problem i have is that I need to scroll to the bottom. So i'm using the page overview. And when I scroll down in that, it crashes

(I just noticed, I hadn't updated my app. Gonna post an update now)

Alright. Even with the update the problem persists.

Still thank you for your work

**Comment by QubaB** [comment]
I was testing it only on android and it was intended to show that big pdf can be loaded and displayed relatively quickly. Now I have better version which handles also saving and opening notes, but it does not work on windows. I am investigating it now. Then I update my pull request for further testing.

**Comment by dreamAviator** [comment]
alright. yeah i didnt want to come off as rude or anything, i‘m sorry

**Comment by QubaB** [comment]
I created new pull request with cache reworked and I hope it works on Windows and Android #1559. If someone try it I will be glad for comments. I am able to open 800 pages pdfs.

**Comment by dreamAviator** [comment]
I kinda have a problem with exporting to pdf if the document is large

**Comment by yuitayuun** [comment]
on my android version it loads in the pdf, keeps loading it, then crashes, then i'm left with 235 blank pages.
on linux it doesn't even try to import it and leaves me with one empty page. really disappointing as that's my main way of working with these types of apps, marking down huge pdfs. am i doing something wrong?

**Comment by yuitayuun** [comment]
it crashes on ios too, not leaving any trace of the notes. i tripple checked and it leaves some pages working randomly on android.

**Comment by bharsgo** [comment]
Yes it does crashes on android tablet even with 16GB RAM
